import Link from "next/link";
import { ArrowDown, ArrowRight, CheckCircle2, ShieldCheck, Sparkles } from "lucide-react";
import { Brand } from "@/components/brand";

const technologies = [
  ["01", "small RNA-seq", "Recupera hipótesis sustentadas por señales regulatorias observadas; no elige un diagnóstico ganador."],
  ["02", "Whole Exome Sequencing", "Prioriza variantes codificantes con calidad, evidencia disponible y revisión humana."],
  ["03", "Whole Genome Sequencing", "Amplía el contexto genómico dentro del alcance técnico que cada piloto puede sostener."],
];

export default function Home() {
  return <main>
    <nav className="nav shell"><Brand /><div className="nav-links"><a href="#como-funciona">Cómo funciona</a><a href="#evidencia">Evidencia</a><a href="#tecnologias">Tecnologías</a></div><Link className="nav-action" href="/login">Crear cuenta <ArrowRight size={15} /></Link></nav>
    <section className="hero shell"><p className="eyebrow"><i /> INTELIGENCIA MOLECULAR</p><h1>Entiende la señal.<br /><em>Explora tu historia molecular.</em></h1><p className="hero-copy">Sapyria traduce datos ómicos complejos en un espacio claro y trazable para comprender el fenotipo molecular que merece ser explorado.</p><div className="hero-actions"><Link className="primary-button" href="/login">Crear mi espacio <ArrowRight size={17} /></Link><a className="text-link" href="#como-funciona">Conocer el enfoque <ArrowDown size={15} /></a></div><div className="hero-visual" aria-hidden="true"><div className="orbit a" /><div className="orbit b" /><div className="orbit c" /><div className="helix">{Array.from({ length: 8 }).map((_, i) => <span key={i} />)}</div><div className="orb one" /><div className="orb two" /><small className="label left">SEÑAL ÓMICA</small><small className="label right">EVIDENCE LAYER</small></div></section>
    <section className="intro shell" id="como-funciona"><p className="section-label">DE ARCHIVO A CONTEXTO</p><div className="intro-grid"><h2>La secuenciación produce datos.<br /><em>La interpretación empieza después.</em></h2><div><p>Sapyria organiza la señal molecular, su calidad técnica y la evidencia disponible en una experiencia comprensible. No sustituye una evaluación médica ni convierte una correlación en diagnóstico.</p><Link href="/login" className="text-link">Explorar la demo <ArrowRight size={15} /></Link></div></div><div className="steps"><article><b>01</b><h3>Señal</h3><p>Identificamos patrones medibles en las capas moleculares disponibles.</p></article><article><b>02</b><h3>Contexto</h3><p>Relacionamos hallazgos, procedencia y límites de cada resultado.</p></article><article><b>03</b><h3>Claridad</h3><p>Presentamos una narrativa que el usuario puede revisar y entender.</p></article></div></section>
    <section className="phenotype"><div className="shell phenotype-grid"><div><p className="section-label">FENOTIPO MOLECULAR</p><h2>No buscamos una etiqueta.<br /><em>Buscamos un estado.</em></h2><p>Un fenotipo molecular es una lectura integrada y acotada de la actividad biológica observada. Puede abrir preguntas; no cierra diagnósticos.</p></div><div className="phenotype-card"><Sparkles size={20} /><span>LECTURA DEMO</span><strong>Señal regulatoria coordinada</strong><p>Hipótesis de procesos moleculares que cuentan con evidencia disponible y requieren contexto adicional.</p><div><i /><i /><i /><i /><i /><i /><i /></div></div></div></section>
    <section className="technology shell" id="tecnologias"><p className="section-label">CAPAS ANALÍTICAS</p><h2>La pregunta define<br />la tecnología.</h2><div className="technology-list">{technologies.map(([number, title, copy]) => <article key={title}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight size={18} /></article>)}</div></section>
    <section className="evidence shell" id="evidencia"><div><p className="section-label">TRANSPARENCIA DE EVIDENCIA</p><h2>Una respuesta también<br />debe mostrar sus límites.</h2></div><div className="evidence-list"><p><CheckCircle2 size={18} /> Cada hallazgo conserva su nivel de evidencia y procedencia.</p><p><ShieldCheck size={18} /> Los datos genómicos pesados permanecen fuera de esta plataforma.</p><p><CheckCircle2 size={18} /> La demo indica lo que sabe, lo que infiere y lo que aún no puede concluir.</p></div></section>
    <section className="closing shell"><p className="section-label">TU ESPACIO SAPYRIA</p><h2>Una muestra.<br /><em>Muchas preguntas bien planteadas.</em></h2><Link className="primary-button" href="/login">Crear cuenta <ArrowRight size={17} /></Link></section>
    <footer className="shell"><Brand /><p>Inteligencia molecular para decisiones mejor informadas.</p><p>© 2026 Sapyria</p></footer>
  </main>;
}
